#----------------------------------------
# GitHub Action Part-1 - Basics
#
# Copyleft (c) by Irina Cher 2024
#----------------------------------------
name: My-GitHubActions_Basics
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{github.sha }}"

on: 
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello world! from testing"

    - name: execute few commands
      run : |
        echo "Hello message1"
        echo "Hello message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"

    - name: List current folder
      run : ls -la

    - name: Git Clone My Repo
      uses: actions/checkout@v1

    - name: List current folder
      run : ls -la
      

  my_deploy:
    runs-on: ubuntu-latest
    needs  : [my_testing]
    env:
      VAR1 : "This is Job Level Variable1"
      VAR2 : "This is Job Level Variable2"

    steps:
    - name: Print Hello Message in Deploy
      run : echo "Hello world! from Deploy job"

    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env :
        LOCAL_VAR: "This is Super local Inviroment variable"
      

    - name: Printing Deployment pacage 
      run : echo "Deploy pacage name is ${{ env.DEPLOY_PACKAGE_NAME }}"

    - name: Lets test some pacages if they are here 1
      run : aws --version
      
    - name: Lets test some pacages if they are here 2
      run : zip --version
